# Generated by Django 2.1.7 on 2019-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrid', models.CharField(max_length=255)),
                ('cid', models.CharField(max_length=255)),
                ('time1', models.CharField(max_length=255)),
                ('time2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TourLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('ipcity', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('verficationCode', models.CharField(max_length=255)),
                ('time1', models.CharField(max_length=255)),
                ('time2', models.CharField(max_length=255)),
                ('registState', models.CharField(max_length=255)),
                ('errortimes', models.CharField(max_length=255)),
                ('registtime', models.CharField(max_length=255)),
                ('isroot', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('ipcity', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
            ],
        ),
    ]
